name: HELLO WORLD CI
#on: [push]
on:
  push:
    paths:
      - "./hello-world/**"
      - ".github/workflows/github-actions-demo.yml"

defaults:
  run:
    working-directory: ./hello-world

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install
        shell: bash
        run: npm install
      - name: run unit test
        shell: bash
        run: npm run test:unit