name: HELLO WORLD CI
#on: [push]
on:
  push:
    paths:
      - "./hello-world/**"
      - ".github/workflows/github-actions-demo.yml"

defaults:
  run:
    working-directory: ./hello-world

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./hello-world/package-lock.json
      - run: npm ci
      - run: npm run test:unit